In [29]:
import numpy as np
class linear(object):
    def __init__(self):
        pass
    def fit(self,x,y):
        m,n=x.shape
        x=x.round(2)
        ones=np.ones((m,1))
        x=np.c_[ones,x]
        #we can also write x=np.c_[np.ones[x.shape[0],1],x]
        if y.ndim ==1:
          y=y.reshape(-1,1)
        #it is used for converting into 2d
        theta=np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)
        self.intercept_=theta[0:1]
        self.coef_=theta[1:]
        return self;
    def predict(self,x):
        x=np.c_[np.ones((x.shape[0],1)),x]
        return x.dot(np.r_[self.intercept_,self.coef_])
from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing()
housing.data
type(housing.data)
housing.data.shape


In [30]:
import pandas  as pd

In [3]:
housing_df=pd.DataFrame(housing.data,columns=housing.feature_names)

In [4]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [5]:
print(housing.DESCR)
housing.data

California housing dataset.

The original database is available from StatLib

    http://lib.stat.cmu.edu/datasets/

The data contains 20,640 observations on 9 variables.

This dataset contains the average house value as target variable
and the following input variables (features): average income,
housing average age, average rooms, average bedrooms, population,
average occupation, latitude, and longitude in that order.

References
----------

Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
Statistics and Probability Letters, 33 (1997) 291-297.




array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [6]:
housing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
MedInc        20640 non-null float64
HouseAge      20640 non-null float64
AveRooms      20640 non-null float64
AveBedrms     20640 non-null float64
Population    20640 non-null float64
AveOccup      20640 non-null float64
Latitude      20640 non-null float64
Longitude     20640 non-null float64
dtypes: float64(8)
memory usage: 1.3 MB


In [7]:
housing_df.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.350000  
25%        2.429741     33.930000   -121.800000  
50%        2.818116     34.260000   -118.490000  
75%        3.282261     37.710000   -118.010000  
max     1243.333333     41.950000   -114.310000

In [8]:
housing_df.hist(bins=20,figsize=(15,10))

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x000001E488894A58>,
      dtype=object)

In [9]:
m,n=housing.data.shape

In [10]:
indices=np.random.permutation(m)
indices

array([ 4551, 12614,   568, ..., 14232,  5057, 16116])

In [11]:
pos=int(m*0.8)
train_ix=indices[:pos]
train_ix
test_ix=indices[pos:]
test_ix

array([  539, 13313,   219, ..., 14232,  5057, 16116])

In [12]:
train_x=housing.data[train_ix]
train_y=housing.target[train_ix]

test_x=housing.data[test_ix]
test_y=housing.target[test_ix]


In [13]:
train_x.shape
train_y.shape
test_x.shape
test_y.shape


(4128,)

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
lin_reg=LinearRegression()


In [16]:
lin_reg.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
lin_reg.coef_

array([ 4.36958685e-01,  9.65225418e-03, -1.00817517e-01,  6.06413409e-01,
       -3.03778173e-06, -3.44272970e-03, -4.19809643e-01, -4.32190073e-01])

In [18]:
lin_reg.intercept_

-36.71911258840411

In [19]:
lin_reg.predict([train_x[0]])

array([0.93638855])

In [20]:
train_y[0]

1.813

In [21]:
my_lin=linear()

In [22]:
my_lin.fit(train_x,train_y)

In [23]:
my_lin.coef_


array([[ 4.36900154e-01],
       [ 9.65400899e-03],
       [-1.00701534e-01],
       [ 6.05852462e-01],
       [-3.03677759e-06],
       [-3.44227777e-03],
       [-4.19779206e-01],
       [-4.32146169e-01]])

In [24]:
my_lin.intercept_

array([[-36.71479291]])

In [25]:
my_lin.predict(train_x[0:1])

array([[0.93624166]])

In [26]:
train_x[0:1]

array([[ 8.28800000e-01,  1.30000000e+01,  2.54559043e+00,
         1.04185351e+00,  1.82300000e+03,  2.72496263e+00,
         3.40500000e+01, -1.18240000e+02]])

In [27]:
train=my_lin.predict(train_x)

In [28]:
from sklearn.metrics import mean_squared_error
mean_squared_error(train,train_y)

0.5190421936567619